In [8]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# data = yf.download('BTC-USD', start='2024-01-01', end='2025-04-01')
# data.to_csv('btc.csv')
data = pd.read_csv('./btc.csv')
# data.drop('Unnamed: 0', axis=1, inplace=True)
data = data.drop(index=[0,1])
data.head()

,Price,Close,High,Low,Open,Volume
2,2024-01-01,44167.33203125,44175.4375,42214.9765625,42280.234375,18426978443
3,2024-01-02,44957.96875,45899.70703125,44176.94921875,44187.140625,39335274536
4,2024-01-03,42848.17578125,45503.2421875,40813.53515625,44961.6015625,46342323118
5,2024-01-04,44179.921875,44770.0234375,42675.17578125,42855.81640625,30448091210
6,2024-01-05,44162.69140625,44353.28515625,42784.71875,44192.98046875,32336029347

In [10]:
df = data[['Price','Close']].copy()

# df['day'] = range(1, len(df) + 1)
# df['Close'] = df['Close'].astype(float)

df['1D'] = df['Close'].shift(1)
df['2D'] = df['Close'].shift(2)
df['3D'] = df['Close'].shift(3)
df['4D'] = df['Close'].shift(4)
df['5D'] = df['Close'].shift(5)
df['6D'] = df['Close'].shift(6)

df.dropna(inplace=True)
df.head()

,Price,Close,1D,2D,3D,4D,5D,6D
8,2024-01-07,43943.09765625,43989.1953125,44162.69140625,44179.921875,42848.17578125,44957.96875,44167.33203125
9,2024-01-08,46970.50390625,43943.09765625,43989.1953125,44162.69140625,44179.921875,42848.17578125,44957.96875
10,2024-01-09,46139.73046875,46970.50390625,43943.09765625,43989.1953125,44162.69140625,44179.921875,42848.17578125
11,2024-01-10,46627.77734375,46139.73046875,46970.50390625,43943.09765625,43989.1953125,44162.69140625,44179.921875
12,2024-01-11,46368.5859375,46627.77734375,46139.73046875,46970.50390625,43943.09765625,43989.1953125,44162.69140625

In [11]:
X = df[['1D','2D','3D','4D','5D','6D']]
y = df['Close']

In [12]:
X.head()

,1D,2D,3D,4D,5D,6D
8,43989.1953125,44162.69140625,44179.921875,42848.17578125,44957.96875,44167.33203125
9,43943.09765625,43989.1953125,44162.69140625,44179.921875,42848.17578125,44957.96875
10,46970.50390625,43943.09765625,43989.1953125,44162.69140625,44179.921875,42848.17578125
11,46139.73046875,46970.50390625,43943.09765625,43989.1953125,44162.69140625,44179.921875
12,46627.77734375,46139.73046875,46970.50390625,43943.09765625,43989.1953125,44162.69140625

In [13]:
y.head()

8     43943.09765625
9     46970.50390625
10    46139.73046875
11    46627.77734375
12     46368.5859375
Name: Close, dtype: object

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [15]:
from sklearn.ensemble import RandomForestRegressor


model = RandomForestRegressor(n_estimators=200, random_state=0)
model.fit(X_train, y_train)

print("Train R²:", model.score(X_train, y_train))
print("Test R²:", model.score(X_test, y_test))

Train R²: 0.9973160307498324
Test R²: 0.6790381249261852

In [19]:
df.tail()

,Price,Close,1D,2D,3D,4D,5D,6D
453,2025-03-27,87177.1015625,86900.8828125,87471.703125,87498.9140625,86054.375,83832.484375,84043.2421875
454,2025-03-28,84353.1484375,87177.1015625,86900.8828125,87471.703125,87498.9140625,86054.375,83832.484375
455,2025-03-29,82597.5859375,84353.1484375,87177.1015625,86900.8828125,87471.703125,87498.9140625,86054.375
456,2025-03-30,82334.5234375,82597.5859375,84353.1484375,87177.1015625,86900.8828125,87471.703125,87498.9140625
457,2025-03-31,82548.9140625,82334.5234375,82597.5859375,84353.1484375,87177.1015625,86900.8828125,87471.703125

In [18]:
# d2 = yf.download('BTC-USD', start='2025-04-01', end='2025-04-30')
# d2.to_csv('btc2.csv')
d2 = pd.read_csv('./btc2.csv')
d2 = d2.drop(index=[0,1])
d2.head()

,Price,Close,High,Low,Open,Volume
2,2025-04-01,85169.171875,85487.3671875,82429.359375,82551.921875,28175650319
3,2025-04-02,82485.7109375,88466.953125,82343.5390625,85180.609375,47584398470
4,2025-04-03,83102.828125,83909.296875,81282.1015625,82487.4765625,36852112080
5,2025-04-04,83843.8046875,84696.1484375,81670.75,83100.25,45157640207
6,2025-04-05,83504.796875,84207.015625,82377.734375,83844.703125,14380803631

In [26]:
# x_input = pd.DataFrame([[82548, 82334, 82592, 84353, 87177, 86900]],
                    #    columns=X.columns)   # keep feature names
x_input = df.iloc[-1, 2:]
x_input = pd.DataFrame([x_input.values], columns=X.columns)

pred = model.predict(x_input)[0]
print(pred)

89793.18375

In [ ]:
# # Get last 6 closes
# last_known = df['Close'].iloc[-6:].tolist()

# future_preds = []
# for _ in range(5):   # predict 5 future days
#     # lag_1 = most recent, lag_6 = oldest
#     X_input = pd.DataFrame([last_known[-6:]], columns=X.columns)  # keep same feature names
#     pred = model.predict(X_input)[0]
#     future_preds.append(pred)
    
#     # Append prediction so it becomes lag_1 for the next iteration
#     last_known.append(pred)

# print("Future predictions:", future_preds)

Future predictions: [np.float64(89302.8264453125), np.float64(89520.5560546875), np.float64(89906.790859375), np.float64(90892.3173828125), np.float64(91461.9225)]

In [ ]:
result = pd.DataFrame()
result['date'] = data['Price'][:5]
result['real'] = data['Close'][:5]
result['predicted'] = [i for i in future_preds]
result