In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from  sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder, OrdinalEncoder, MinMaxScaler, RobustScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression
df = pd.read_csv('./housing[1].csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [47]:
# ord_scaler = OrdinalEncoder()
# df['ocean_proximity'] = ord_scaler.fit_transform(df[['ocean_proximity']])

# df["ocean_proximity"] = df["ocean_proximity"].map({"<1H OCEAN": 1, "INLAND": 2, "NEAR OCEAN": 3, "NEAR BAY": 4, "ISLAND": 5})
# df[["ocean_proximity"]].value_counts()

In [48]:
scaler = StandardScaler()
df['longitude'] = scaler.fit_transform(np.array(df['longitude'].values).reshape(-1,1))
df['population'] = scaler.fit_transform(np.array(df['population'].values).reshape(-1,1))
df['households'] = scaler.fit_transform(np.array(df['households'].values).reshape(-1,1))
df["total_bedrooms"] = df["total_bedrooms"].fillna(df["total_bedrooms"].mean(numeric_only=True))

df_encoded = df
df_encoded = pd.get_dummies(df, columns=["ocean_proximity"])
df_encoded.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-1.327835,37.88,41.0,880.0,129.0,-0.974429,-0.977033,8.3252,452600.0,False,False,False,True,False
1,-1.322844,37.86,21.0,7099.0,1106.0,0.861439,1.669961,8.3014,358500.0,False,False,False,True,False
2,-1.332827,37.85,52.0,1467.0,190.0,-0.820777,-0.843637,7.2574,352100.0,False,False,False,True,False
3,-1.337818,37.85,52.0,1274.0,235.0,-0.766028,-0.733781,5.6431,341300.0,False,False,False,True,False
4,-1.337818,37.85,52.0,1627.0,280.0,-0.759847,-0.629157,3.8462,342200.0,False,False,False,True,False

In [49]:
x = df_encoded.drop("median_house_value", axis=1).iloc[:, :].values
y = np.array(df["median_house_value"].values).reshape(-1, 1)

# poly = PolynomialFeatures(degree=1)
# x_poly = poly.fit_transform(x)
# x_train, x_test, y_train, y_test = train_test_split(x_poly, y, test_size=0.2, random_state=0)

# model = LinearRegression()
# model.fit(x_train, y_train)
# print(model.score(x_train, y_train))
# print(model.score(x_test, y_test))

In [50]:
model = make_pipeline(
    PolynomialFeatures(degree=3),
    LinearRegression()
)

x = df_encoded.drop(columns=['median_house_value'], axis=1)
y = df[['median_house_value']].values
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, test_size=0.2)
model.fit(x_train, y_train)
print(model.score(x_train, y_train))
print(model.score(x_test, y_test))

0.745168192666946
0.7336973152399623

In [51]:
# from lazypredict.Supervised import LazyRegressor
# from sklearn.model_selection import train_test_split

# model = LazyRegressor(verbose=0, ignore_warnings=True, custom_metric=None)
# models, predictions = model.fit(x_train, x_test, y_train, y_test)
# print(models)

In [52]:
# model = make_pipeline(
#     PolynomialFeatures(degree=3),
#     LinearRegression()
# )

# x = df.drop(columns=['median_house_value'], axis=1)
# y = df[['median_house_value']].values
# x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, test_size=0.2)
# model.fit(x_train, y_train)
# print(model.score(x_test, y_test))

In [53]:
# sns.heatmap(df.corr().abs(), annot= True, cmap='coolwarm')

In [54]:
# sns.pairplot(df, hue='ocean_proximity');

In [55]:
# sns.scatterplot(x= df['longitude'], y = df['latitude'], hue=df['ocean_proximity'])